using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using griffel_femex.Geometry;
using griffel_femex.Interop;
using griffel_femex.Loads;
using griffel_femex.Loads.Combinations;
using SAF.DataAccess.Models.Enums;
using SAF.DataAccess.Models.Loads;

namespace griffel_femex.Adapters.Saf
{
    public sealed partial class SafImporter
    {
        // ---- Groups, cases, combinations ---------------------------------------

        private static void ImportLoadCases(FemexModel model, SafObjects objects, SafIndex index,
                                            SafMessageLog log)
        {
            int groupId = 1;
            foreach (ExcelStructuralLoadGroup source in objects.LoadGroups)
            {
                LoadGroupType type = SafEnums.ToFemex(source.LoadGroupType, out bool exact);
                var group = new LoadGroup
                {
                    Id = groupId++,
                    Uid = SafIdentity.UidOf(source),
                    Name = source.Name,
                    Type = type,
                    Relation = SafEnums.ToFemex(source.Relation),
                };

                model.LoadGroups.Add(group);
                if (!string.IsNullOrEmpty(source.Name))
                    index.LoadGroups[source.Name!] = group;

                if (!exact)
                {
                    log.Object(SafLoss.ApproximatedLoadGroupType,
                               new ObjectRef(FemexEntity.LoadGroup, group.Id, group.Uid), source.Name,
                               $"The workbook states {source.LoadGroupType}.");
                }

                if (source.Load is not null)
                    log.Concept(SafLoss.DroppedLoadGroupCategory);
            }

            int number = 1;
            foreach (ExcelStructuralLoadCase source in objects.LoadCases)
            {
                var loadCase = new LoadCase
                {
                    Number = number++,
                    Uid = SafIdentity.UidOf(source),
                    Label = source.Name,
                    Nature = SafEnums.ToFemex(source.ActionType, source.LoadType),
                    LoadGroupId = Lookup(index.LoadGroups, source.LoadGroup)?.Id,

                    // SAF has no self-weight load object: it is a load case whose
                    // Load type says so, generated by the receiver. FEMEX says the
                    // same thing with a dimensionless factor on the case.
                    SelfWeightFactor = source.LoadType == ExcelLoadCaseType.SelfWeight ? 1.0 : 0.0,
                };

                model.LoadCases.Add(loadCase);
                if (!string.IsNullOrEmpty(source.Name))
                    index.LoadCases[source.Name!] = loadCase;

                if (source.Duration.HasValue)
                    log.Concept(SafLoss.DroppedLoadCaseDuration);

                // The group the case names may be one the exporter synthesised for
                // it, in which case the reference itself is an invention.
                if (loadCase.LoadGroupId.HasValue && source.LoadGroup is not null &&
                    source.LoadGroup.StartsWith("LG-", StringComparison.Ordinal))
                {
                    log.Concept(SafLoss.AttachedToInventedLoadGroup);
                }
            }

            int combination = 1;
            foreach (ExcelStructuralLoadCombination source in objects.LoadCombinations)
            {
                LimitState state = SafEnums.ToFemex(source.Category, out bool exactCategory);
                var target = new LoadCombination
                {
                    Number = combination++,
                    Uid = SafIdentity.UidOf(source),
                    Label = source.Name,
                    LimitState = state,
                    CombinationType = SafEnums.ToFemex(source.Type),
                };

                var reference = new ObjectRef(FemexEntity.LoadCombination, target.Number, target.Uid);

                string[] cases = source.LoadCases ?? new string[0];
                double?[] factors = source.LoadFactors ?? new double?[0];
                double?[] multipliers = source.LoadMultipliers ?? new double?[0];

                bool collapsed = false;
                for (int i = 0; i < cases.Length; i++)
                {
                    LoadCase? named = Lookup(index.LoadCases, cases[i]);
                    if (named is null)
                        continue;

                    double factor = i < factors.Length ? factors[i] ?? 1.0 : 1.0;
                    double multiplier = i < multipliers.Length ? multipliers[i] ?? 1.0 : 1.0;
                    if (Math.Abs(multiplier - 1.0) > 1e-12)
                        collapsed = true;

                    target.Terms.Add(new LoadCombinationTerm
                    {
                        LoadCaseNumber = named.Number,
                        Factor = factor * multiplier,
                    });
                }

                model.LoadCombinations.Add(target);

                if (collapsed)
                    log.Object(SafLoss.CollapsedCombinationFactor, reference, source.Name);

                if (!exactCategory)
                {
                    log.Object(SafLoss.UnrepresentableCombinationCategory, reference, source.Name,
                               source.NationalStandard.HasValue
                                   ? $"The standard named is {source.NationalStandard.Value}."
                                   : null);
                }

                if (source.Type == ExcelLoadCaseCombinationType.NonLinear)
                    log.Object(SafLoss.DroppedNonLinearCombination, reference, source.Name);

                if (source.NationalStandard.HasValue)
                    log.Concept(SafLoss.DroppedNationalStandard);
            }
        }

        // ---- Loads -------------------------------------------------------------

        private static void ImportLoads(FemexModel model, SafObjects objects, SafIndex index,
                                        SafMessageLog log)
        {
            var geometry = new SafGeometry(model);
            int id = 1;

            ImportPointLoads(model, objects, index, log, geometry, ref id);
            ImportLinearLoads(model, objects, index, log, geometry, ref id);
            ImportAreaLoads(model, objects, index, log, ref id);
            ImportThermalLoads(model, objects, index, log, ref id);
        }

        /// <summary>
        /// SAF splits force from moment into two sheets with two Ids; FEMEX carries
        /// Fx..Mz on one object. So a force and a moment at the same station in the
        /// same case merge, and one of the two SAF uids cannot survive the merge.
        /// </summary>
        private static void ImportPointLoads(FemexModel model, SafObjects objects, SafIndex index,
                                             SafMessageLog log, SafGeometry geometry, ref int id)
        {
            var byStation = new Dictionary<string, PointLoad>(StringComparer.Ordinal);
            int next = id;
            bool localFrame = false;

            foreach (ExcelStructuralPointAction action in objects.PointActions)
            {
                localFrame |= action.CoordinateSystem == ExcelCoordinateSystem.Local ||
                              action.Direction == ExcelActionDirection.Vector;

                double value = SafUnits.Newtons(action.Value);
                Emit(action, action.Name, load =>
                {
                    switch (action.Direction)
                    {
                        case ExcelActionDirection.X: load.Fx += value; break;
                        case ExcelActionDirection.Y: load.Fy += value; break;
                        default: load.Fz += value; break;
                    }
                });
            }

            foreach (ExcelStructuralPointMoment moment in objects.PointMoments)
            {
                localFrame |= moment.CoordinateSystem == ExcelCoordinateSystem.Local;

                double value = SafUnits.NewtonMetres(moment.Value);
                Emit(moment, moment.Name, load =>
                {
                    switch (moment.Direction)
                    {
                        case ExcelMomentDirection.Mx: load.Mx += value; break;
                        case ExcelMomentDirection.Mz: load.Mz += value; break;
                        default: load.My += value; break;
                    }
                });
            }

            id = next;

            if (localFrame)
                log.Concept(SafLoss.DroppedPointLoadFrame);

            void Emit<T>(T source, string? handle, Action<PointLoad> apply)
                where T : SAF.DataAccess.Models.ExcelObjectBase,
                          SAF.DataAccess.Models.Interfaces.IExcelPointStructuralReference
            {
                LoadCase? loadCase = Lookup(index.LoadCases, LoadCaseOf(source));
                if (loadCase is null)
                    return;

                Bar? bar = null;
                Node? node = null;
                double? position = null;
                bool chorded = false;

                if (source.ForceAction == ExcelPointForceAction.OnBeam)
                {
                    bar = Lookup(index.Bars, source.ReferenceMember);
                    if (bar is null)
                        return;

                    position = SafPosition.Relative(source.PositionX, source.CoordinateDefinition,
                                                    source.Origin, geometry.LengthOf(bar), out chorded);
                }
                else
                {
                    node = Lookup(index.Nodes, source.ReferenceNode);
                    if (node is null)
                        return;
                }

                // Repeat (n) and Delta x: one SAF row standing for n loads at a fixed
                // spacing. Expanding is numerically exact and loses the grouping, so
                // each expanded load points back at the row it came from.
                int repeat = Math.Max(1, source.Repeat ?? 1);
                double delta = DeltaOf(source, bar, geometry);

                for (int i = 0; i < repeat; i++)
                {
                    double? station = position.HasValue ? position.Value + i * delta : (double?)null;
                    string key = string.Join("|", loadCase.Number.ToString(CultureInfo.InvariantCulture),
                                             bar?.Id.ToString(CultureInfo.InvariantCulture) ?? "-",
                                             node?.NodeNumber.ToString(CultureInfo.InvariantCulture) ?? "-",
                                             station?.ToString("R", CultureInfo.InvariantCulture) ?? "-");

                    if (!byStation.TryGetValue(key, out PointLoad? load))
                    {
                        load = new PointLoad
                        {
                            Id = next++,
                            Uid = i == 0
                                ? SafIdentity.UidOf(source)
                                : DerivedUid(SafIdentity.UidOf(source), i),
                            ParentUid = i == 0 ? null : SafIdentity.UidOf(source),
                            Label = repeat > 1
                                ? handle + " (" + (i + 1).ToString(CultureInfo.InvariantCulture) + " of " +
                                  repeat.ToString(CultureInfo.InvariantCulture) + ")"
                                : handle,
                            LoadCaseNumber = loadCase.Number,
                            NodeNumber = node?.NodeNumber ?? 0,
                            BarId = bar?.Id,
                            Position = station,
                        };

                        byStation[key] = load;
                        model.Loads.Add(load);
                    }
                    else
                    {
                        log.Object(SafLoss.MergedForceAndMoment,
                                   new ObjectRef(FemexEntity.Load, load.Id, load.Uid), handle,
                                   $"It merged with {load.Label}.");
                    }

                    apply(load);

                    if (i == 0 && chorded)
                    {
                        log.Object(SafLoss.ChordedPosition,
                                   new ObjectRef(FemexEntity.Load, load.Id, load.Uid), handle);
                    }
                }

                if (repeat > 1)
                {
                    log.Object(SafLoss.ExpandedRepeatSeries,
                               new ObjectRef(FemexEntity.Load, next - repeat), handle,
                               $"{repeat} loads, spaced {source.DeltaX}.");
                }
            }
        }

        private static string? LoadCaseOf(object source)
        {
            return source switch
            {
                ExcelStructuralPointAction a => a.LoadCase,
                ExcelStructuralPointMoment m => m.LoadCase,
                _ => null,
            };
        }

        private static double DeltaOf(SAF.DataAccess.Models.Interfaces.IExcelPointStructuralReference source,
                                      Bar? bar, SafGeometry geometry)
        {
            if (source.DeltaX is null || bar is null)
                return 0.0;

            if (source.DeltaX is UnitsNet.Length absolute)
            {
                double length = geometry.LengthOf(bar);
                return length > 0.0 ? absolute.Meters / length : 0.0;
            }

            return source.DeltaX is double relative ? relative : 0.0;
        }

        /// <summary>
        /// Line loads and line moments, which merge for the same reason point loads
        /// do: SAF splits them into two sheets and <c>LinearLoad</c> carries both a
        /// magnitude and a moment.
        /// </summary>
        private static void ImportLinearLoads(FemexModel model, SafObjects objects, SafIndex index,
                                              SafMessageLog log, SafGeometry geometry, ref int id)
        {
            var byRun = new Dictionary<string, LinearLoad>(StringComparer.Ordinal);
            bool eccentric = false;
            int next = id;

            foreach (ExcelStructuralCurveAction source in objects.CurveActions)
            {
                eccentric |= NonZero(source.EccentricityEy) || NonZero(source.EccentricityEz);

                LinearLoad? load = Placed(source.LoadCase, source.ForceAction, source.Member,
                                          source.MemberRib, source.Member2D, source.Member2DRegion,
                                          source.Member2DOpening, source.Edge, source.CoordinateDefinition,
                                          source.Origin, source.StartPoint, source.EndPoint,
                                          source.Extent, source.Name, SafIdentity.UidOf(source), ref next);
                if (load is null)
                    continue;

                load.CoordinateSystem = SafEnums.ToFemex(source.CoordinateSystem);
                load.Direction = SafEnums.ToFemex(source.Direction);
                load.Projected = source.Location == ExcelLocation.Projection;
                load.MagnitudeStart = SafUnits.NewtonsPerMetre(source.Value);
                load.MagnitudeEnd = source.Distribution == ExcelCurveDistribution.Trapezoidal
                    ? SafUnits.NewtonsPerMetre(source.Value2)
                    : load.MagnitudeStart;
            }

            foreach (ExcelStructuralCurveMoment source in objects.CurveMoments)
            {
                LinearLoad? load = Placed(source.LoadCase, source.ForceAction, source.Member,
                                          source.MemberRib, source.Member2D, source.Member2DRegion,
                                          source.Member2DOpening, source.Edge, source.CoordinateDefinition,
                                          source.Origin, source.StartPoint, source.EndPoint,
                                          source.Extent, source.Name, SafIdentity.UidOf(source), ref next);
                if (load is null)
                    continue;

                load.MomentStart = SafUnits.NewtonMetresPerMetre(source.Value1);
                load.MomentEnd = source.Distribution == ExcelCurveDistribution.Trapezoidal
                    ? SafUnits.NewtonMetresPerMetre(source.Value2)
                    : load.MomentStart;
            }

            id = next;

            if (eccentric)
                log.Concept(SafLoss.DroppedLoadEccentricity);

            LinearLoad? Placed(string? loadCaseName, ExcelCurveForceAction? action, string? member,
                               string? rib, string? surface, string? region, string? opening, int? edge,
                               ExcelCoordinateDefinition? definition, ExcelOrigin? origin,
                               object? start, object? end, ExcelExtentOfForceOnBeam? extent,
                               string? handle, Guid? uid, ref int nextId)
            {
                LoadCase? loadCase = Lookup(index.LoadCases, loadCaseName);
                if (loadCase is null)
                    return null;

                Bar? bar = null;
                List<int>? edgeNodes = null;
                int? plateId = null;
                int? regionId = null;

                switch (action)
                {
                    case ExcelCurveForceAction.OnBeam:
                        bar = Lookup(index.Bars, member);
                        break;
                    case ExcelCurveForceAction.OnRib:
                        bar = Lookup(index.Bars, rib);
                        break;
                    case ExcelCurveForceAction.OnInternalEdge:
                        return null; // Reported once, per concept, as UnmappedInternalEdge.
                    default:
                        var host = EdgeOf(index, surface, region, opening, edge, oneBased: true);
                        if (host is not null)
                        {
                            edgeNodes = host.Value.Nodes;
                            plateId = host.Value.PlateId;
                            regionId = host.Value.RegionId;
                        }
                        break;
                }

                if (bar is null && edgeNodes is null)
                    return null;

                // The host the stations are measured along: the bar, or the edge
                // segment itself. Measuring an edge-hosted load against a bar length
                // of zero is what put "0 to 1" — the full extent, and no
                // information — on eleven of the house workbook's loads.
                double length = bar is not null
                    ? geometry.LengthOf(bar)
                    : geometry.DistanceBetween(edgeNodes![0], edgeNodes[1]);

                double? from = null;
                double? to = null;
                bool chorded = false;

                if (extent == ExcelExtentOfForceOnBeam.Span || SafPosition.IsPartial(start, end, definition))
                {
                    from = SafPosition.Relative(start, definition, origin, length, out bool a);
                    to = SafPosition.Relative(end, definition, origin, length, out bool b);
                    chorded = a || b;

                    if (origin == ExcelOrigin.FromEnd && from.HasValue && to.HasValue && from > to)
                        (from, to) = (to, from);
                }

                // An extent stated as a length can reach past the end of the one
                // contour edge a FEMEX load names — the house workbook's LFS3 runs
                // 2.5 m along a 2 m opening edge. A station outside 0 to 1 is not
                // something a receiver can act on, so it is cut at the edge and the
                // cut is declared, rather than written out as a number with no rule.
                bool clamped = bar is null && (Clamp(ref from) | Clamp(ref to));

                string key = string.Join("|",
                    loadCase.Number.ToString(CultureInfo.InvariantCulture),
                    bar?.Id.ToString(CultureInfo.InvariantCulture) ?? "-",
                    plateId?.ToString(CultureInfo.InvariantCulture) ?? "-",
                    regionId?.ToString(CultureInfo.InvariantCulture) ?? "-",
                    edgeNodes is null ? "-" : string.Join(",", edgeNodes),
                    from?.ToString("R", CultureInfo.InvariantCulture) ?? "-",
                    to?.ToString("R", CultureInfo.InvariantCulture) ?? "-");

                if (byRun.TryGetValue(key, out LinearLoad? existing))
                {
                    log.Object(SafLoss.MergedForceAndMoment,
                               new ObjectRef(FemexEntity.Load, existing.Id, existing.Uid), handle,
                               $"It merged with {existing.Label}.");
                    return existing;
                }

                var load = new LinearLoad
                {
                    Id = nextId++,
                    Uid = uid,
                    Label = handle,
                    LoadCaseNumber = loadCase.Number,
                    BarId = bar?.Id,
                    PlateId = bar is null ? plateId : null,
                    RegionId = bar is null ? regionId : null,
                    StartNode = bar?.StartNodeId ?? edgeNodes![0],
                    EndNode = bar?.EndNodeId ?? edgeNodes![1],
                    StartPosition = from,
                    EndPosition = to,
                };

                byRun[key] = load;
                model.Loads.Add(load);

                if (chorded)
                {
                    log.Object(SafLoss.ChordedPosition,
                               new ObjectRef(FemexEntity.Load, load.Id, load.Uid), handle);
                }

                if (clamped)
                {
                    log.Object(SafLoss.ClampedEdgeExtent,
                               new ObjectRef(FemexEntity.Load, load.Id, load.Uid), handle);
                }

                return load;
            }
        }

        /// <summary>
        /// A relative station brought back inside the host it is measured along, and
        /// whether it had to move. The caller declares the move; this only makes it.
        /// </summary>
        private static bool Clamp(ref double? position)
        {
            if (position is not double value || (value >= 0.0 && value <= 1.0))
                return false;

            position = value < 0.0 ? 0.0 : 1.0;
            return true;
        }

        private static bool NonZero(UnitsNet.Length? value)
        {
            return value.HasValue && Math.Abs(value.Value.Meters) > 1e-12;
        }

        private static void ImportAreaLoads(FemexModel model, SafObjects objects, SafIndex index,
                                            SafMessageLog log, ref int id)
        {
            foreach (ExcelStructuralSurfaceAction source in objects.SurfaceActions)
            {
                LoadCase? loadCase = Lookup(index.LoadCases, source.LoadCase);
                if (loadCase is null)
                    continue;

                Plate? plate = Lookup(index.Plates, source.Member2DReference)
                               ?? Lookup(index.Plates, source.Member2DDistributionReference);
                int? regionId = null;

                if (source.Member2DRegionReference is not null &&
                    index.Regions.TryGetValue(source.Member2DRegionReference, out var region))
                {
                    plate ??= region.Plate;
                    regionId = region.Region.Id;
                }

                if (plate is null)
                    continue;

                model.Loads.Add(new AreaLoad
                {
                    Id = id++,
                    Uid = SafIdentity.UidOf(source),
                    Label = source.Name,
                    LoadCaseNumber = loadCase.Number,
                    PlateId = plate.Id,
                    RegionId = regionId,
                    CoordinateSystem = SafEnums.ToFemex(source.CoordinateSystem),
                    Direction = SafEnums.ToFemex(source.Direction),
                    Projected = source.Location == ExcelLocation.Projection,
                    Magnitude = SafUnits.Pascals(source.Value),
                });
            }
        }

        /// <summary>
        /// SAF states a linear thermal variation as up to four fibre temperatures;
        /// FEMEX states a mean change and two signed gradients. Four numbers become
        /// three, which is a real reduction and is reported as one.
        /// </summary>
        private static void ImportThermalLoads(FemexModel model, SafObjects objects, SafIndex index,
                                               SafMessageLog log, ref int id)
        {
            foreach (ExcelStructuralCurveActionThermal source in objects.CurveThermals)
            {
                LoadCase? loadCase = Lookup(index.LoadCases, source.LoadCase);
                Bar? bar = Lookup(index.Bars, source.Member) ?? Lookup(index.Bars, source.MemberRib);
                if (loadCase is null || bar is null)
                    continue;

                var load = new TemperatureLoad
                {
                    Id = id++,
                    Uid = SafIdentity.UidOf(source),
                    Label = source.Name,
                    LoadCaseNumber = loadCase.Number,
                    ElementIds = { bar.Id },
                };

                if (source.Variation == ExcelTemperatureVariation.Linear)
                {
                    double top = SafUnits.DegreesCelsius(source.TempT);
                    double bottom = SafUnits.DegreesCelsius(source.TempB);
                    double left = SafUnits.DegreesCelsius(source.TempL);
                    double right = SafUnits.DegreesCelsius(source.TempR);

                    load.DeltaT = (top + bottom + left + right) / 4.0;
                    load.GradientZ = top - bottom;
                    load.GradientY = right - left;

                    log.Object(SafLoss.CollapsedThermalVariation,
                               new ObjectRef(FemexEntity.Load, load.Id, load.Uid), source.Name);
                }
                else
                {
                    load.DeltaT = SafUnits.DegreesCelsius(source.DeltaT);
                }

                model.Loads.Add(load);
            }

            foreach (ExcelStructuralSurfaceActionThermal source in objects.SurfaceThermals)
            {
                LoadCase? loadCase = Lookup(index.LoadCases, source.LoadCase);
                Plate? plate = Lookup(index.Plates, source.Member2D);
                if (loadCase is null || plate is null)
                    continue;

                double first = SafUnits.DegreesCelsius(source.Value1);
                var load = new TemperatureLoad
                {
                    Id = id++,
                    Uid = SafIdentity.UidOf(source),
                    Label = source.Name,
                    LoadCaseNumber = loadCase.Number,
                    ElementIds = { plate.Id },
                    DeltaT = first,
                };

                if (source.Variation == ExcelTemperatureVariation.Linear)
                {
                    double second = SafUnits.DegreesCelsius(source.Value2);
                    load.DeltaT = (first + second) / 2.0;
                    load.GradientZ = first - second;

                    log.Object(SafLoss.CollapsedThermalVariation,
                               new ObjectRef(FemexEntity.Load, load.Id, load.Uid), source.Name);
                }

                model.Loads.Add(load);
            }
        }
    }
}
